modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="fortissimum" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Fortissimum" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Naxanria" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Endgame mod
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.fortissimum]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.fortissimum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
